name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # Run only on version tag pushes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential libsqlite3-dev pkg-config

      - name: Configure project with CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: |
          cmake --build build --config Release

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/apex-bank
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
